### ISSUE TITLE
Make a through-hole only version

### ISSUE THREAD

**Issue by jtcmedia** [MicroJoe/espboard#2]
Really nice little board you have here. It would be great if there was a through-hole only version for those DIY who don't want to mess with SMT. Looks like there is enough space on the board to do so.

**Comment by gagath** [comment]
Hello there and thanks for your feedback.

This board was designed for using spare ESP-1 that I had in stock. Since this circuit is working very well I do not expect to make any change to this design since I only needed few of these boards. The project is open hardware so I invite you to clone the repository and open it with KiCAD in order to replace the LM1117-3.3 voltage regulator with a through-hole footprint.

I have been doing 2+ years of hobby electronic designs and I am progressively replacing through-hole only designs with mixed designs. SMD are way cheaper than their TH counterparts and take less space on circuit (got 100 LM1117-3.3 SMD for less than 4 €).
