### ISSUE TITLE
Opening the espboard in KiCad produces libraries not found errors

### ISSUE THREAD

**Issue by jtcmedia** [MicroJoe/espboard#3]
When opening the schematic in KiCad, the following window pops-up:
![KiCad Error](https://s9.postimg.org/n4x5p3apr/kicad-error.png)

I am assuming these are custom components you made?

**Comment by gagath** [comment]
The d1_mini_kicad should not be needed because the board does not use D1 Mini in any ways. Probably a test of mine. Elsewise the usb_connector is effectively a custom design for [this AliExpress part](https://www.aliexpress.com/item/10pcs-MICRO-USB-to-DIP-Adapter-5pin-female-connector-B-type-pcb-converter-pinboard-2https://www.aliexpress.com/item/10pcs-MICRO-USB-to-DIP-Adapter-5pin-female-connector-B-typehttps://www.aliexpress.com/item/10pcs-MICRO-USB-to-DIP-Adapter-5pin-female-connector-B-type-pcb-converter-pinboard-2-54/32667278609.html-pcb-converter-pinboard-2-54/32667278609.html-54/32667278609.html).

I'll just drop a .zip here, I am not maintaining this board but it is free hardware project so you can fork it if you want to fix it for other people.

[usb_connector.zip](https://github.com/MicroJoe/espboard/files/1760140/usb_connector.zip)

**Comment by jtcmedia** [comment]
Great, thanks!!
